"""initial

Revision ID: bd6564c8bd40
Revises: 
Create Date: 2026-06-02 09:12:31.550689
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'bd6564c8bd40'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('specializations', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rating_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractors'))
    )
    op.create_index(op.f('ix_contractors_inn'), 'contractors', ['inn'], unique=True)
    op.create_index(op.f('ix_contractors_name'), 'contractors', ['name'], unique=False)
    op.create_table('work_types',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('WORKOVER', 'OVERHAUL', 'ROUTINE', 'EMERGENCY', 'INSTALLATION', name='work_category'), nullable=False),
    sa.Column('planned_duration_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('applies_to_equipment_type', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_types'))
    )
    op.create_index(op.f('ix_work_types_category'), 'work_types', ['category'], unique=False)
    op.create_index(op.f('ix_work_types_code'), 'work_types', ['code'], unique=True)
    op.create_table('checklist_templates',
    sa.Column('work_type_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], name=op.f('fk_checklist_templates_work_type_id_work_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_templates')),
    sa.UniqueConstraint('work_type_id', name=op.f('uq_checklist_templates_work_type_id'))
    )
    op.create_table('contractor_ratings',
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='rating_period'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('orders_total', sa.Integer(), nullable=False),
    sa.Column('orders_completed', sa.Integer(), nullable=False),
    sa.Column('orders_auto_confirmed', sa.Integer(), nullable=False),
    sa.Column('orders_rejected', sa.Integer(), nullable=False),
    sa.Column('repeat_visits', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('timeliness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weights_json', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_contractor_ratings_contractor_id_contractors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractor_ratings'))
    )
    op.create_index(op.f('ix_contractor_ratings_contractor_id'), 'contractor_ratings', ['contractor_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'TECHNOLOGIST', 'MASTER', 'CONTRACTOR', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_users_contractor_id_contractors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_contractor_id'), 'users', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('checklist_steps',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Enum('BOOLEAN', 'NUMERIC', 'TEXT', 'PHOTO', 'CHOICE', name='step_data_type'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('norm_json', sa.JSON(), nullable=True),
    sa.Column('telemetry_param', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], name=op.f('fk_checklist_steps_template_id_checklist_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_steps'))
    )
    op.create_index(op.f('ix_checklist_steps_template_id'), 'checklist_steps', ['template_id'], unique=False)
    op.create_table('objects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('CLUSTER', 'WELL', 'FACILITY', name='object_kind'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['objects.id'], name=op.f('fk_objects_parent_id_objects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], name=op.f('fk_objects_responsible_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objects'))
    )
    op.create_index(op.f('ix_objects_code'), 'objects', ['code'], unique=True)
    op.create_index(op.f('ix_objects_kind'), 'objects', ['kind'], unique=False)
    op.create_index(op.f('ix_objects_name'), 'objects', ['name'], unique=False)
    op.create_index(op.f('ix_objects_parent_id'), 'objects', ['parent_id'], unique=False)
    op.create_table('equipment',
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('USHGN', 'UECN', 'WELLHEAD', 'PUMP_UNIT', 'SEPARATOR', 'OTHER', name='equipment_type'), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('commissioned_at', sa.Date(), nullable=True),
    sa.Column('nominal_params_json', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name=op.f('fk_equipment_object_id_objects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment'))
    )
    op.create_index(op.f('ix_equipment_object_id'), 'equipment', ['object_id'], unique=False)
    op.create_index(op.f('ix_equipment_serial_number'), 'equipment', ['serial_number'], unique=True)
    op.create_index(op.f('ix_equipment_type'), 'equipment', ['type'], unique=False)
    op.create_table('work_orders',
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('work_type_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ASSIGNED', 'IN_PROGRESS', 'SUBMITTED', 'AUTO_CONFIRMED', 'CONFIRMED', 'REJECTED', 'DELAYED_VERIFICATION', 'VERIFIED', 'ISSUE_FOUND', 'CANCELLED', name='work_order_status'), nullable=False),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_work_orders_assigned_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_work_orders_contractor_id_contractors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name=op.f('fk_work_orders_object_id_objects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], name=op.f('fk_work_orders_work_type_id_work_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders'))
    )
    op.create_index(op.f('ix_work_orders_contractor_id'), 'work_orders', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_work_orders_number'), 'work_orders', ['number'], unique=True)
    op.create_index(op.f('ix_work_orders_object_id'), 'work_orders', ['object_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_work_type_id'), 'work_orders', ['work_type_id'], unique=False)
    op.create_table('acts',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('contractor_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'AUTO_CONFIRMED', 'CONFIRMED', 'REJECTED', 'DELAYED_VERIFICATION', 'VERIFIED', 'ISSUE_FOUND', name='act_status'), nullable=False),
    sa.Column('actual_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('actual_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('actual_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telemetry_before_json', sa.JSON(), nullable=True),
    sa.Column('telemetry_after_json', sa.JSON(), nullable=True),
    sa.Column('auto_check_passed', sa.Boolean(), nullable=True),
    sa.Column('auto_check_score', sa.Float(), nullable=True),
    sa.Column('auto_check_details', sa.JSON(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], name=op.f('fk_acts_confirmed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_user_id'], ['users.id'], name=op.f('fk_acts_contractor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_acts_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acts'))
    )
    op.create_index(op.f('ix_acts_contractor_user_id'), 'acts', ['contractor_user_id'], unique=False)
    op.create_index(op.f('ix_acts_status'), 'acts', ['status'], unique=False)
    op.create_index(op.f('ix_acts_work_order_id'), 'acts', ['work_order_id'], unique=False)
    op.create_table('telemetry_readings',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.Enum('SCRAPE', 'EVENT', 'SNAPSHOT', name='telemetry_kind'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_telemetry_readings_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_readings'))
    )
    op.create_index('ix_telemetry_equipment_observed', 'telemetry_readings', ['equipment_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_telemetry_readings_equipment_id'), 'telemetry_readings', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_telemetry_readings_observed_at'), 'telemetry_readings', ['observed_at'], unique=False)
    op.create_table('checklist_responses',
    sa.Column('act_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], name=op.f('fk_checklist_responses_act_id_acts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['checklist_steps.id'], name=op.f('fk_checklist_responses_step_id_checklist_steps'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_responses'))
    )
    op.create_index(op.f('ix_checklist_responses_act_id'), 'checklist_responses', ['act_id'], unique=False)
    op.create_index(op.f('ix_checklist_responses_step_id'), 'checklist_responses', ['step_id'], unique=False)
    op.create_table('photos',
    sa.Column('act_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('BEFORE', 'AFTER', 'ISSUE', 'OTHER', name='photo_kind'), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('exif_json', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], name=op.f('fk_photos_act_id_acts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index(op.f('ix_photos_act_id'), 'photos', ['act_id'], unique=False)
    op.create_index(op.f('ix_photos_kind'), 'photos', ['kind'], unique=False)
    op.create_index(op.f('ix_photos_sha256'), 'photos', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_sha256'), table_name='photos')
    op.drop_index(op.f('ix_photos_kind'), table_name='photos')
    op.drop_index(op.f('ix_photos_act_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_checklist_responses_step_id'), table_name='checklist_responses')
    op.drop_index(op.f('ix_checklist_responses_act_id'), table_name='checklist_responses')
    op.drop_table('checklist_responses')
    op.drop_index(op.f('ix_telemetry_readings_observed_at'), table_name='telemetry_readings')
    op.drop_index(op.f('ix_telemetry_readings_equipment_id'), table_name='telemetry_readings')
    op.drop_index('ix_telemetry_equipment_observed', table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    op.drop_index(op.f('ix_acts_work_order_id'), table_name='acts')
    op.drop_index(op.f('ix_acts_status'), table_name='acts')
    op.drop_index(op.f('ix_acts_contractor_user_id'), table_name='acts')
    op.drop_table('acts')
    op.drop_index(op.f('ix_work_orders_work_type_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_object_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_contractor_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_equipment_type'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_serial_number'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_object_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_objects_parent_id'), table_name='objects')
    op.drop_index(op.f('ix_objects_name'), table_name='objects')
    op.drop_index(op.f('ix_objects_kind'), table_name='objects')
    op.drop_index(op.f('ix_objects_code'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_checklist_steps_template_id'), table_name='checklist_steps')
    op.drop_table('checklist_steps')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_contractor_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contractor_ratings_contractor_id'), table_name='contractor_ratings')
    op.drop_table('contractor_ratings')
    op.drop_table('checklist_templates')
    op.drop_index(op.f('ix_work_types_code'), table_name='work_types')
    op.drop_index(op.f('ix_work_types_category'), table_name='work_types')
    op.drop_table('work_types')
    op.drop_index(op.f('ix_contractors_name'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_inn'), table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###
